import Foundation
import MCP

// MARK: - Errors (always compiled)

/// Errors thrown by the MCP ↔ Foundation Models bridge layer.
///
/// All cases carry a human-readable `errorDescription` via `LocalizedError`.
public enum MCPBridgeError: Error, LocalizedError {

    /// The JSON produced by the on-device model could not be parsed as a
    /// `[String: Any]` dictionary before forwarding to the MCP server.
    case invalidArgumentsJSON(String)

    /// A transport-level or MCP handshake failure occurred while connecting
    /// to the specified server.
    case connectionFailed(String, underlying: Error)

    /// The MCP tool's JSON Schema could not be converted to a
    /// `DynamicGenerationSchema` for use by Foundation Models.
    case schemaConversionFailed(String, underlying: Error)

    /// The MCP server returned an error response when the tool was called.
    case toolCallFailed(String, underlying: Error)

    public var errorDescription: String? {
        switch self {
        case .invalidArgumentsJSON(let detail):
            return "Invalid arguments JSON from model: \(detail)"
        case .connectionFailed(let server, let error):
            return "Failed to connect to MCP server '\(server)': \(error.localizedDescription)"
        case .schemaConversionFailed(let tool, let error):
            return "Failed to build GenerationSchema for tool '\(tool)': \(error.localizedDescription)"
        case .toolCallFailed(let tool, let error):
            return "MCP tool '\(tool)' call failed: \(error.localizedDescription)"
        }
    }
}

// MARK: - MCP.Value helpers (always compiled)

extension MCP.Value {
    /// Creates a `Value` from a plain `Any` returned by `JSONSerialization`.
    ///
    /// Handles all JSON primitives: `null`, `Bool`, `Int`, `Double`, `String`,
    /// `[Any]`, and `[String: Any]`. Any other type is coerced to a `String`.
    init(anyValue value: Any) throws {
        switch value {
        case is NSNull:          self = .null
        case let b as Bool:      self = .bool(b)
        case let i as Int:       self = .int(i)
        case let d as Double:    self = .double(d)
        case let s as String:    self = .string(s)
        case let arr as [Any]:
            self = try .array(arr.map { try MCP.Value(anyValue: $0) })
        case let dict as [String: Any]:
            self = try .object(dict.mapValues { try MCP.Value(anyValue: $0) })
        default:
            self = .string("\(value)")
        }
    }
}

// MARK: - FoundationModels Bridge
// Compiled only when the iOS 26 / macOS 26 SDK is present.
// No @Generable macro required — schemas are built at runtime via DynamicGenerationSchema.

#if canImport(FoundationModels)
import FoundationModels

// MARK: - Argument Container

/// The argument container for every dynamic MCP tool wrapper.
///
/// Manually conforms to `ConvertibleFromGeneratedContent` so no `@Generable`
/// macro is needed. The on-device model populates a `GeneratedContent` value
/// whose structure is driven by the per-tool `GenerationSchema` built from
/// the MCP JSON Schema at init time.
///
/// - Note: The `content` value is extracted as JSON via `jsonString` and
///   forwarded to the MCP server by `MCPDynamicTool.call(arguments:)`.
@available(iOS 26.0, macOS 26.0, visionOS 26.0, *)
public struct MCPToolArguments: ConvertibleFromGeneratedContent, Sendable {

    /// The raw content generated by the on-device model for this tool call.
    public let content: GeneratedContent

    public init(_ content: GeneratedContent) throws {
        self.content = content
    }
}

// MARK: - Dynamic Tool Wrapper

/// A Foundation Models `Tool` that wraps a runtime-discovered MCP tool.
///
/// `MCPDynamicTool` bridges a single `MCP.Tool` to the `FoundationModels.Tool`
/// protocol without any `@Generable` macro. The argument schema is built at
/// runtime using `DynamicGenerationSchema`.
///
/// ## Tool Call Flow
/// 1. Foundation Models generates a `GeneratedContent` shaped by `parameters`.
/// 2. `call(arguments:)` extracts it as JSON via `GeneratedContent.jsonString`.
/// 3. The JSON is parsed into `[String: MCP.Value]` by `ArgumentParser`.
/// 4. The arguments are forwarded to the MCP server via `client.callTool(...)`.
/// 5. The MCP response is converted to `String` by `ResultConverter`.
///
/// - Note: If the tool call fails at the MCP level, `call(arguments:)` returns
///   a graceful `[error] ...` string rather than throwing, so the model can
///   reason about the failure without crashing the session.
@available(iOS 26.0, macOS 26.0, visionOS 26.0, *)
public struct MCPDynamicTool: FoundationModels.Tool {
    public typealias Arguments = MCPToolArguments
    public typealias Output    = String         // String: PromptRepresentable

    /// The sanitised tool name used by Foundation Models (alphanumeric + `_`).
    public let name: String

    /// Human-readable description including the full MCP parameter schema.
    public let description: String

    /// The runtime-built argument schema for Foundation Models.
    public let parameters: GenerationSchema

    private let client:  MCP.Client
    private let mcpName: String

    init(mcpTool: MCP.Tool, client: MCP.Client) throws {
        self.client  = client
        self.mcpName = mcpTool.name
        self.name    = MCPDynamicTool.sanitisedName(mcpTool.name)
        self.description = SchemaConverter.buildToolDescription(for: mcpTool)
        do {
            self.parameters = try SchemaConverter.buildGenerationSchema(for: mcpTool)
        } catch {
            throw MCPBridgeError.schemaConversionFailed(mcpTool.name, underlying: error)
        }
    }

    // MARK: - Tool conformance

    /// Calls the MCP tool with the model-generated arguments.
    ///
    /// Errors at the MCP layer are caught and returned as a `[error] …` string
    /// so the `LanguageModelSession` can continue reasoning rather than throwing.
    public func call(arguments: MCPToolArguments) async throws -> String {
        let jsonStr = arguments.content.jsonString
        let mcpArgs: [String: MCP.Value]
        do {
            mcpArgs = try ArgumentParser.parse(jsonStr)
        } catch {
            // Argument parsing failure is a hard error — the schema is broken.
            throw error
        }

        do {
            let (content, isError) = try await client.callTool(
                name:      mcpName,
                arguments: mcpArgs.isEmpty ? nil : mcpArgs
            )
            return ResultConverter.string(from: content, isError: isError)
        } catch {
            // Tool call failures are returned as a readable error string so the
            // model can report the issue rather than crashing the session.
            MCPLogger.error(MCPLogger.bridge, "Tool '\(mcpName)' call failed: \(error)")
            return ResultConverter.toolCallError(tool: mcpName, error: error)
        }
    }

    // MARK: - Helpers

    /// Replaces characters outside `[a-zA-Z0-9_]` with underscores so the name
    /// is valid as a Foundation Models tool identifier.
    static func sanitisedName(_ raw: String) -> String {
        raw.unicodeScalars.map { scalar in
            let c = Character(scalar)
            return (c.isLetter || c.isNumber || scalar == "_") ? String(scalar) : "_"
        }.joined()
    }
}

#endif // canImport(FoundationModels)
