import Foundation
import MCP

// MARK: - Errors (always compiled)

/// Errors thrown by the MCP ↔ Foundation Models bridge layer.
public enum MCPBridgeError: Error, LocalizedError {
    case invalidArgumentsJSON(String)
    case connectionFailed(String, underlying: Error)
    case schemaConversionFailed(String, underlying: Error)

    public var errorDescription: String? {
        switch self {
        case .invalidArgumentsJSON(let detail):
            return "Invalid arguments JSON from model: \(detail)"
        case .connectionFailed(let server, let error):
            return "Failed to connect to MCP server '\(server)': \(error.localizedDescription)"
        case .schemaConversionFailed(let tool, let error):
            return "Failed to build GenerationSchema for tool '\(tool)': \(error.localizedDescription)"
        }
    }
}

// MARK: - MCP.Value helpers (always compiled)

extension MCP.Value {
    /// Creates a `Value` from a plain `Any` returned by `JSONSerialization`.
    init(anyValue value: Any) throws {
        switch value {
        case is NSNull:          self = .null
        case let b as Bool:      self = .bool(b)
        case let i as Int:       self = .int(i)
        case let d as Double:    self = .double(d)
        case let s as String:    self = .string(s)
        case let arr as [Any]:
            self = try .array(arr.map { try MCP.Value(anyValue: $0) })
        case let dict as [String: Any]:
            self = try .object(dict.mapValues { try MCP.Value(anyValue: $0) })
        default:
            self = .string("\(value)")
        }
    }
}

// MARK: - FoundationModels Bridge
// Compiled only when the iOS 26 / macOS 26 SDK is present.
// No @Generable macro required — schemas are built at runtime via DynamicGenerationSchema.

#if canImport(FoundationModels)
import FoundationModels

// MARK: - Argument Container

/// The argument container for every dynamic MCP tool wrapper.
///
/// Manually conforms to `ConvertibleFromGeneratedContent` so no `@Generable`
/// macro is needed. The on-device model populates a `GeneratedContent` value
/// whose structure is driven by the per-tool `GenerationSchema` built from
/// the MCP JSON Schema at init time.
@available(iOS 26.0, macOS 26.0, visionOS 26.0, *)
public struct MCPToolArguments: ConvertibleFromGeneratedContent, Sendable {
    /// The raw content generated by the on-device model for this tool call.
    public let content: GeneratedContent

    public init(_ content: GeneratedContent) throws {
        self.content = content
    }
}

// MARK: - Dynamic Tool Wrapper

/// A Foundation Models `Tool` that wraps a runtime-discovered MCP tool.
///
/// - `parameters` is built from the MCP JSON Schema via `DynamicGenerationSchema`
///   — no `@Generable` macro required.
/// - `call(arguments:)` extracts the model's output as JSON and forwards it
///   to the MCP server, returning the result as a plain `String`.
@available(iOS 26.0, macOS 26.0, visionOS 26.0, *)
public struct MCPDynamicTool: FoundationModels.Tool {
    public typealias Arguments = MCPToolArguments
    public typealias Output    = String         // String: PromptRepresentable

    public let name: String
    public let description: String
    public let parameters: GenerationSchema

    private let client:  MCP.Client
    private let mcpName: String

    init(mcpTool: MCP.Tool, client: MCP.Client) throws {
        self.client  = client
        self.mcpName = mcpTool.name
        self.name    = MCPDynamicTool.sanitisedName(mcpTool.name)
        self.description = SchemaConverter.buildToolDescription(for: mcpTool)
        do {
            self.parameters = try SchemaConverter.buildGenerationSchema(for: mcpTool)
        } catch {
            throw MCPBridgeError.schemaConversionFailed(mcpTool.name, underlying: error)
        }
    }

    // MARK: - Tool conformance

    public func call(arguments: MCPToolArguments) async throws -> String {
        let jsonStr  = arguments.content.jsonString
        let mcpArgs  = try parseArguments(jsonStr)
        let (content, isError) = try await client.callTool(
            name:      mcpName,
            arguments: mcpArgs.isEmpty ? nil : mcpArgs
        )
        return ResultConverter.string(from: content, isError: isError)
    }

    // MARK: - Helpers

    private func parseArguments(_ json: String) throws -> [String: MCP.Value] {
        let trimmed = json.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, trimmed != "{}", trimmed != "null" else { return [:] }

        guard let data = trimmed.data(using: .utf8) else {
            throw MCPBridgeError.invalidArgumentsJSON("Could not encode string as UTF-8")
        }
        let raw = try JSONSerialization.jsonObject(with: data)
        guard let dict = raw as? [String: Any] else {
            throw MCPBridgeError.invalidArgumentsJSON("Top-level value must be a JSON object")
        }
        return try dict.reduce(into: [:]) { acc, pair in
            acc[pair.key] = try MCP.Value(anyValue: pair.value)
        }
    }

    /// Replaces characters outside `[a-zA-Z0-9_]` with underscores.
    private static func sanitisedName(_ raw: String) -> String {
        raw.unicodeScalars.map { scalar in
            let c = Character(scalar)
            return (c.isLetter || c.isNumber || scalar == "_") ? String(scalar) : "_"
        }.joined()
    }
}

#endif // canImport(FoundationModels)
